import type { Metadata } from "next";

export const metadata: Metadata = {
  title:
    "Massage Services Bunbury - Remedial, Sports & Pregnancy Massage | Bunbury Wellness",
  description:
    "Professional massage services in Bunbury, WA. Remedial massage, sports massage, pregnancy massage, and dry needling therapy. Female massage therapists available. Book your session today.",
  keywords: [
    "massage services Bunbury",
    "remedial massage Bunbury",
    "sports massage Bunbury",
    "pregnancy massage Bunbury",
    "dry needling Bunbury",
    "massage therapy services Bunbury",
    "female massage therapist Bunbury",
    "massage therapist services Bunbury",
    "therapeutic massage Bunbury",
    "prenatal massage Bunbury",
    "sports massage therapy Bunbury",
    "remedial massage therapy Bunbury",
    "massage for pain relief Bunbury",
    "massage for athletes Bunbury",
    "pregnancy massage therapy Bunbury",
    "massage appointment Bunbury",
    "book massage Bunbury",
    "massage clinic services Bunbury",
    "deep tissue massage Bunbury",
    "trigger point therapy Bunbury",
    "myofascial release Bunbury",
    "massage for back pain Bunbury",
    "massage for neck pain Bunbury",
    "massage for shoulder pain Bunbury",
    "sports injury massage Bunbury",
    "post workout massage Bunbury",
    "prenatal massage therapy Bunbury",
    "pregnancy safe massage Bunbury",
    "dry needling therapy Bunbury",
    "acupuncture massage Bunbury",
    "massage near me Bunbury",
    "best massage therapist Bunbury",
    "qualified massage therapist Bunbury",
    "registered massage therapist Bunbury",
    "massage therapy clinic Bunbury",
    "wellness center Bunbury",
    "health and wellness Bunbury",
    "physical therapy Bunbury",
    "injury recovery massage Bunbury",
    "chronic pain massage Bunbury",
    "stress relief massage Bunbury",
    "relaxation massage Bunbury",
    "therapeutic touch Bunbury",
    "manual therapy Bunbury",
    "soft tissue therapy Bunbury",
    "muscle tension relief Bunbury",
    "posture correction massage Bunbury",
    "workplace injury massage Bunbury",
    "repetitive strain massage Bunbury",
    "whiplash massage therapy Bunbury",
    "headache massage therapy Bunbury",
    "migraine relief massage Bunbury",
    "fibromyalgia massage Bunbury",
    "arthritis massage therapy Bunbury",
    "sciatica massage therapy Bunbury",
    "hip pain massage Bunbury",
    "knee pain massage Bunbury",
    "foot massage therapy Bunbury",
    "hand massage therapy Bunbury",
    "carpal tunnel massage Bunbury",
    "tennis elbow massage Bunbury",
    "golfer elbow massage Bunbury",
    "rotator cuff massage Bunbury",
    "frozen shoulder massage Bunbury",
    "TMJ massage therapy Bunbury",
    "jaw pain massage Bunbury",
    "massage for sleep problems Bunbury",
    "massage for anxiety Bunbury",
    "massage for depression Bunbury",
    "prenatal wellness Bunbury",
    "postnatal massage Bunbury",
    "new mother massage Bunbury",
    "baby massage Bunbury",
    "infant massage Bunbury",
    "children massage therapy Bunbury",
    "teen massage therapy Bunbury",
    "senior massage therapy Bunbury",
    "elderly massage therapy Bunbury",
    "palliative care massage Bunbury",
    "cancer support massage Bunbury",
    "lymphedema massage Bunbury",
    "diabetes massage therapy Bunbury",
    "high blood pressure massage Bunbury",
    "heart condition massage Bunbury",
    "pregnancy complications massage Bunbury",
    "high risk pregnancy massage Bunbury",
    "multiple pregnancy massage Bunbury",
    "breastfeeding support massage Bunbury",
    "lactation massage Bunbury",
    "postpartum recovery massage Bunbury",
    "cesarean recovery massage Bunbury",
    "episiotomy recovery massage Bunbury",
    "pelvic floor massage Bunbury",
    "abdominal massage therapy Bunbury",
    "digestive massage therapy Bunbury",
    "constipation massage Bunbury",
    "IBS massage therapy Bunbury",
    "menstrual pain massage Bunbury",
    "endometriosis massage Bunbury",
    "PCOS massage therapy Bunbury",
    "menopause massage therapy Bunbury",
    "hormonal imbalance massage Bunbury",
    "thyroid massage therapy Bunbury",
    "adrenal fatigue massage Bunbury",
    "chronic fatigue massage Bunbury",
    "ME/CFS massage therapy Bunbury",
    "fibromyalgia massage therapy Bunbury",
    "lupus massage therapy Bunbury",
    "rheumatoid arthritis massage Bunbury",
    "osteoarthritis massage Bunbury",
    "osteoporosis massage therapy Bunbury",
    "scoliosis massage therapy Bunbury",
    "kyphosis massage therapy Bunbury",
    "lordosis massage therapy Bunbury",
    "flat feet massage Bunbury",
    "high arches massage Bunbury",
    "bunions massage therapy Bunbury",
    "plantar fasciitis massage Bunbury",
    "heel spurs massage Bunbury",
    "Achilles tendon massage Bunbury",
    "shin splints massage Bunbury",
    "IT band massage therapy Bunbury",
    "piriformis massage therapy Bunbury",
    "psoas massage therapy Bunbury",
    "quadriceps massage therapy Bunbury",
    "hamstring massage therapy Bunbury",
    "calf massage therapy Bunbury",
    "glute massage therapy Bunbury",
    "hip flexor massage Bunbury",
    "adductor massage therapy Bunbury",
    "abductor massage therapy Bunbury",
    "tensor fascia latae massage Bunbury",
    "sartorius massage therapy Bunbury",
    "gracilis massage therapy Bunbury",
    "pectineus massage therapy Bunbury",
    "obturator massage therapy Bunbury",
    "gemellus massage therapy Bunbury",
    "quadratus femoris massage Bunbury",
    "vastus lateralis massage Bunbury",
    "vastus medialis massage Bunbury",
    "vastus intermedius massage Bunbury",
    "rectus femoris massage Bunbury",
    "biceps femoris massage Bunbury",
    "semitendinosus massage Bunbury",
    "semimembranosus massage Bunbury",
    "gastrocnemius massage Bunbury",
    "soleus massage therapy Bunbury",
    "tibialis anterior massage Bunbury",
    "tibialis posterior massage Bunbury",
    "peroneus longus massage Bunbury",
    "peroneus brevis massage Bunbury",
    "extensor digitorum longus massage Bunbury",
    "extensor hallucis longus massage Bunbury",
    "flexor digitorum longus massage Bunbury",
    "flexor hallucis longus massage Bunbury",
    "abductor hallucis massage Bunbury",
    "flexor digitorum brevis massage Bunbury",
    "abductor digiti minimi massage Bunbury",
    "quadratus plantae massage Bunbury",
    "lumbricals massage therapy Bunbury",
    "interossei massage therapy Bunbury",
    "adductor hallucis massage Bunbury",
    "flexor hallucis brevis massage Bunbury",
    "adductor digiti minimi massage Bunbury",
    "opponens digiti minimi massage Bunbury",
    "flexor digiti minimi brevis massage Bunbury",
    "abductor pollicis brevis massage Bunbury",
    "flexor pollicis brevis massage Bunbury",
    "opponens pollicis massage Bunbury",
    "adductor pollicis massage Bunbury",
    "flexor pollicis longus massage Bunbury",
    "extensor pollicis longus massage Bunbury",
    "extensor pollicis brevis massage Bunbury",
    "abductor pollicis longus massage Bunbury",
    "extensor indicis massage Bunbury",
    "extensor digitorum massage Bunbury",
    "extensor digiti minimi massage Bunbury",
    "extensor carpi ulnaris massage Bunbury",
    "extensor carpi radialis longus massage Bunbury",
    "extensor carpi radialis brevis massage Bunbury",
    "supinator massage therapy Bunbury",
    "brachioradialis massage Bunbury",
    "extensor carpi radialis massage Bunbury",
    "pronator teres massage Bunbury",
    "flexor carpi radialis massage Bunbury",
    "palmaris longus massage Bunbury",
    "flexor carpi ulnaris massage Bunbury",
    "flexor digitorum superficialis massage Bunbury",
    "flexor digitorum profundus massage Bunbury",
    "flexor pollicis longus massage Bunbury",
    "pronator quadratus massage Bunbury",
    "brachialis massage therapy Bunbury",
    "biceps brachii massage Bunbury",
    "triceps brachii massage Bunbury",
    "anconeus massage therapy Bunbury",
    "coracobrachialis massage Bunbury",
    "deltoid massage therapy Bunbury",
    "supraspinatus massage Bunbury",
    "infraspinatus massage therapy Bunbury",
    "teres minor massage Bunbury",
    "teres major massage Bunbury",
    "subscapularis massage Bunbury",
    "serratus anterior massage Bunbury",
    "pectoralis major massage Bunbury",
    "pectoralis minor massage Bunbury",
    "subclavius massage therapy Bunbury",
    "sternocleidomastoid massage Bunbury",
    "scalene massage therapy Bunbury",
    "levator scapulae massage Bunbury",
    "rhomboid major massage Bunbury",
    "rhomboid minor massage Bunbury",
    "trapezius massage therapy Bunbury",
    "latissimus dorsi massage Bunbury",
    "erector spinae massage Bunbury",
    "multifidus massage therapy Bunbury",
    "rotatores massage therapy Bunbury",
    "interspinales massage Bunbury",
    "intertransversarii massage Bunbury",
    "longissimus massage therapy Bunbury",
    "iliocostalis massage therapy Bunbury",
    "spinalis massage therapy Bunbury",
    "semispinalis massage therapy Bunbury",
    "splenius capitis massage Bunbury",
    "splenius cervicis massage Bunbury",
    "longus capitis massage Bunbury",
    "longus colli massage Bunbury",
    "rectus capitis anterior massage Bunbury",
    "rectus capitis lateralis massage Bunbury",
    "obliquus capitis superior massage Bunbury",
    "obliquus capitis inferior massage Bunbury",
    "rectus capitis posterior major massage Bunbury",
    "rectus capitis posterior minor massage Bunbury",
    "massage therapy education Bunbury",
    "massage therapy training Bunbury",
    "massage therapy certification Bunbury",
    "massage therapy license Bunbury",
    "massage therapy insurance Bunbury",
    "massage therapy benefits Bunbury",
    "massage therapy research Bunbury",
    "massage therapy studies Bunbury",
    "massage therapy evidence Bunbury",
    "massage therapy science Bunbury",
    "massage therapy techniques Bunbury",
    "massage therapy methods Bunbury",
    "massage therapy approaches Bunbury",
    "massage therapy styles Bunbury",
    "massage therapy modalities Bunbury",
    "massage therapy treatments Bunbury",
    "massage therapy protocols Bunbury",
    "massage therapy procedures Bunbury",
    "massage therapy assessments Bunbury",
    "massage therapy evaluations Bunbury",
    "massage therapy consultations Bunbury",
    "massage therapy screenings Bunbury",
    "massage therapy examinations Bunbury",
    "massage therapy diagnoses Bunbury",
    "massage therapy plans Bunbury",
    "massage therapy goals Bunbury",
    "massage therapy outcomes Bunbury",
    "massage therapy results Bunbury",
    "massage therapy effectiveness Bunbury",
    "massage therapy success Bunbury",
    "massage therapy improvement Bunbury",
    "massage therapy progress Bunbury",
    "massage therapy recovery Bunbury",
    "massage therapy rehabilitation Bunbury",
    "massage therapy restoration Bunbury",
    "massage therapy healing Bunbury",
    "massage therapy wellness Bunbury",
    "massage therapy health Bunbury",
    "massage therapy fitness Bunbury",
    "massage therapy performance Bunbury",
    "massage therapy optimization Bunbury",
    "massage therapy enhancement Bunbury",
    "massage therapy maintenance Bunbury",
    "massage therapy prevention Bunbury",
    "massage therapy protection Bunbury",
    "massage therapy support Bunbury",
    "massage therapy care Bunbury",
    "massage therapy service Bunbury",
    "massage therapy practice Bunbury",
    "massage therapy clinic Bunbury",
    "massage therapy center Bunbury",
    "massage therapy facility Bunbury",
    "massage therapy studio Bunbury",
    "massage therapy spa Bunbury",
    "massage therapy salon Bunbury",
    "massage therapy business Bunbury",
    "massage therapy company Bunbury",
    "massage therapy organization Bunbury",
    "massage therapy association Bunbury",
    "massage therapy society Bunbury",
    "massage therapy group Bunbury",
    "massage therapy team Bunbury",
    "massage therapy staff Bunbury",
    "massage therapy personnel Bunbury",
    "massage therapy professionals Bunbury",
    "massage therapy specialists Bunbury",
    "massage therapy experts Bunbury",
    "massage therapy practitioners Bunbury",
    "massage therapy therapists Bunbury",
    "massage therapy technicians Bunbury",
    "massage therapy assistants Bunbury",
    "massage therapy students Bunbury",
    "massage therapy interns Bunbury",
    "massage therapy trainees Bunbury",
    "massage therapy apprentices Bunbury",
    "massage therapy volunteers Bunbury",
    "massage therapy mentors Bunbury",
    "massage therapy supervisors Bunbury",
    "massage therapy managers Bunbury",
    "massage therapy directors Bunbury",
    "massage therapy owners Bunbury",
    "massage therapy founders Bunbury",
    "massage therapy creators Bunbury",
    "massage therapy developers Bunbury",
    "massage therapy designers Bunbury",
    "massage therapy planners Bunbury",
    "massage therapy coordinators Bunbury",
    "massage therapy administrators Bunbury",
    "massage therapy executives Bunbury",
    "massage therapy leaders Bunbury",
    "massage therapy guides Bunbury",
    "massage therapy instructors Bunbury",
    "massage therapy teachers Bunbury",
    "massage therapy educators Bunbury",
    "massage therapy trainers Bunbury",
    "massage therapy coaches Bunbury",
    "massage therapy consultants Bunbury",
    "massage therapy advisors Bunbury",
    "massage therapy counselors Bunbury",
    "massage therapy therapists Bunbury",
    "massage therapy healers Bunbury",
    "massage therapy caregivers Bunbury",
    "massage therapy providers Bunbury",
    "massage therapy servers Bunbury",
    "massage therapy helpers Bunbury",
    "massage therapy supporters Bunbury",
    "massage therapy assistants Bunbury",
    "massage therapy aides Bunbury",
    "massage therapy workers Bunbury",
    "massage therapy employees Bunbury",
    "massage therapy staff Bunbury",
    "massage therapy personnel Bunbury",
    "massage therapy team Bunbury",
    "massage therapy crew Bunbury",
    "massage therapy group Bunbury",
    "massage therapy unit Bunbury",
    "massage therapy department Bunbury",
    "massage therapy division Bunbury",
    "massage therapy section Bunbury",
    "massage therapy branch Bunbury",
    "massage therapy office Bunbury",
    "massage therapy location Bunbury",
    "massage therapy site Bunbury",
    "massage therapy place Bunbury",
    "massage therapy venue Bunbury",
    "massage therapy establishment Bunbury",
    "massage therapy institution Bunbury",
    "massage therapy organization Bunbury",
    "massage therapy corporation Bunbury",
    "massage therapy enterprise Bunbury",
    "massage therapy venture Bunbury",
    "massage therapy operation Bunbury",
    "massage therapy service Bunbury",
    "massage therapy business Bunbury",
    "massage therapy company Bunbury",
    "massage therapy firm Bunbury",
    "massage therapy agency Bunbury",
    "massage therapy bureau Bunbury",
    "massage therapy office Bunbury",
    "massage therapy headquarters Bunbury",
    "massage therapy base Bunbury",
    "massage therapy center Bunbury",
    "massage therapy hub Bunbury",
    "massage therapy station Bunbury",
    "massage therapy post Bunbury",
    "massage therapy point Bunbury",
    "massage therapy spot Bunbury",
    "massage therapy area Bunbury",
    "massage therapy zone Bunbury",
    "massage therapy region Bunbury",
    "massage therapy district Bunbury",
    "massage therapy neighborhood Bunbury",
    "massage therapy community Bunbury",
    "massage therapy city Bunbury",
    "massage therapy town Bunbury",
    "massage therapy suburb Bunbury",
    "massage therapy village Bunbury",
    "massage therapy hamlet Bunbury",
    "massage therapy settlement Bunbury",
    "massage therapy locality Bunbury",
    "massage therapy vicinity Bunbury",
    "massage therapy surroundings Bunbury",
    "massage therapy environment Bunbury",
    "massage therapy setting Bunbury",
    "massage therapy context Bunbury",
    "massage therapy situation Bunbury",
    "massage therapy condition Bunbury",
    "massage therapy circumstance Bunbury",
    "massage therapy state Bunbury",
    "massage therapy status Bunbury",
    "massage therapy position Bunbury",
    "massage therapy place Bunbury",
    "massage therapy location Bunbury",
    "massage therapy site Bunbury",
    "massage therapy spot Bunbury",
    "massage therapy point Bunbury",
    "massage therapy position Bunbury",
    "massage therapy station Bunbury",
    "massage therapy post Bunbury",
    "massage therapy base Bunbury",
    "massage therapy center Bunbury",
    "massage therapy hub Bunbury",
    "massage therapy headquarters Bunbury",
    "massage therapy office Bunbury",
    "massage therapy facility Bunbury",
    "massage therapy establishment Bunbury",
    "massage therapy institution Bunbury",
    "massage therapy organization Bunbury",
    "massage therapy corporation Bunbury",
    "massage therapy company Bunbury",
    "massage therapy business Bunbury",
    "massage therapy enterprise Bunbury",
    "massage therapy venture Bunbury",
    "massage therapy operation Bunbury",
    "massage therapy service Bunbury",
    "massage therapy practice Bunbury",
    "massage therapy clinic Bunbury",
    "massage therapy center Bunbury",
    "massage therapy facility Bunbury",
    "massage therapy studio Bunbury",
    "massage therapy spa Bunbury",
    "massage therapy salon Bunbury",
    "massage therapy wellness center Bunbury",
    "massage therapy health center Bunbury",
    "massage therapy medical center Bunbury",
    "massage therapy therapy center Bunbury",
    "massage therapy treatment center Bunbury",
    "massage therapy care center Bunbury",
    "massage therapy healing center Bunbury",
    "massage therapy recovery center Bunbury",
    "massage therapy rehabilitation center Bunbury",
    "massage therapy wellness facility Bunbury",
    "massage therapy health facility Bunbury",
    "massage therapy medical facility Bunbury",
    "massage therapy therapy facility Bunbury",
    "massage therapy treatment facility Bunbury",
    "massage therapy care facility Bunbury",
    "massage therapy healing facility Bunbury",
    "massage therapy recovery facility Bunbury",
    "massage therapy rehabilitation facility Bunbury",
    "massage therapy wellness studio Bunbury",
    "massage therapy health studio Bunbury",
    "massage therapy medical studio Bunbury",
    "massage therapy therapy studio Bunbury",
    "massage therapy treatment studio Bunbury",
    "massage therapy care studio Bunbury",
    "massage therapy healing studio Bunbury",
    "massage therapy recovery studio Bunbury",
    "massage therapy rehabilitation studio Bunbury",
    "massage therapy wellness spa Bunbury",
    "massage therapy health spa Bunbury",
    "massage therapy medical spa Bunbury",
    "massage therapy therapy spa Bunbury",
    "massage therapy treatment spa Bunbury",
    "massage therapy care spa Bunbury",
    "massage therapy healing spa Bunbury",
    "massage therapy recovery spa Bunbury",
    "massage therapy rehabilitation spa Bunbury",
    "massage therapy wellness salon Bunbury",
    "massage therapy health salon Bunbury",
    "massage therapy medical salon Bunbury",
    "massage therapy therapy salon Bunbury",
    "massage therapy treatment salon Bunbury",
    "massage therapy care salon Bunbury",
    "massage therapy healing salon Bunbury",
    "massage therapy recovery salon Bunbury",
    "massage therapy rehabilitation salon Bunbury",
  ],
  openGraph: {
    title: "Massage Services Bunbury - Remedial, Sports & Pregnancy Massage",
    description:
      "Professional massage services in Bunbury, WA. Remedial massage, sports massage, pregnancy massage, and dry needling therapy. Female massage therapists available.",
    url: process.env.NEXT_PUBLIC_BASE_URL
      ? `${String(process.env.NEXT_PUBLIC_BASE_URL).replace(/\/$/, "")}/services`
      : undefined,
    siteName: "Bunbury Wellness",
    images: [
      {
        url: "/og-image.png",
        width: 1200,
        height: 630,
        alt: "Bunbury Wellness - Massage Services",
      },
    ],
    locale: "en_AU",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "Massage Services Bunbury - Remedial, Sports & Pregnancy Massage",
    description:
      "Professional massage services in Bunbury, WA. Remedial massage, sports massage, pregnancy massage, and dry needling therapy.",
    images: ["/og-image.png"],
  },
  alternates: {
    canonical: "/services",
  },
};

export default function ServicesLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return children;
}
